spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB:bank_db}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres_password}
  kafka:
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.example.testbanking.common.dto.TransactionEvent

logging:
  level:
    org.springframework.cache: TRACE
    org.springframework.data.redis: DEBUG
